### ISSUE TITLE
Slash Char before IP 

### ISSUE THREAD

**Issue by Rahulsharma0810** [0xAF/tmux-public-ip#1]
Thanks for the plugin, In my tmux I am getting `\` before IP

![image](https://user-images.githubusercontent.com/9934859/150300092-a9e47b3f-b5d0-4d92-ba11-2f4bb93d01d7.png)

**Comment by 0xAF** [comment]
I've made a change which should fix the problem. Please update the plugin and report if the backslash is still there. Thanks.

**Comment by Rahulsharma0810** [comment]
Great, working now. Do you think adding a country flag / Code is feasible, useful when working on VPN, etc.

Once example : https://ifconfig.co/json

**Comment by 0xAF** [comment]
Hi. I've reworked the plugin from scratch. It is now using ifconfig.co or similar JSON. Please checkout the README to understand how to use the new version of the script.
Thanks for the suggestion.
